# Makefile

# Specific variables
SRCS = src/main.cpp src/Bureaucrat.cpp src/AForm.cpp \
		src/ShrubberyCreationForm.cpp src/RobotomyRequestForm.cpp \
		src/PresidentialPardonForm.cpp
TARGET = bureaucrat

# Include common rules and variables
include ../common.mk