# Makefile

# Specific variables
SRCS = src/main.cpp src/Animal.cpp src/Dog.cpp src/Cat.cpp \
		src/WrongAnimal.cpp src/WrongCat.cpp
TARGET = animal

# Include common rules and variables
include ../common.mk